# Generated by Django 4.2.6 on 2023-10-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('in_progress', 'In_progress')], default='In_progress', max_length=15),
        ),
    ]
