# Generated by Django 4.2.6 on 2023-10-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_problem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(default='In_progress', max_length=15),
        ),
    ]
