# Generated by Django 4.2.6 on 2023-10-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_problem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solution',
            field=models.TextField(default='no solution yet'),
        ),
    ]
