# Generated by Django 4.2.6 on 2023-10-20 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_problem_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='reported_by',
        ),
        migrations.AddField(
            model_name='problem',
            name='assigned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='resolved_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
